# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  path: $Build.SourcesDirectory

- script: declare -a projectList=(
    "$path/src/Services/Catalog/Catalog.API"
    "$path/src/Services/Basket/Basket.API"
    "$path/src/Services/Ordering/Ordering.API"
    "$path/src/Services/Identity/Identity.API"
    "$path/src/Services/Location/Locations.API"
    "$path/src/Services/Marketing/Marketing.API"
    "$path/src/Services/Payment/Payment.API"
    "$path/src/Web/WebMVC"
    "$path/src/Web/WebStatus" );
  displayName: 'Build Project List Array'

- script: for project in "${projectList[@]}"
    do
      echo -e "\e[33mWorking on $path/$project"
      pushd $project
      echo -e "\e[33m\tBuilding and publishing $project"
      dotnet publish -c Release -o obj/Docker/publish --verbosity quiet
      popd
    done;
  displayName: 'Building Each Project'
  