# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: echo $path;
- script: $path="$(pwd)/../src";
- script: echo $path;

- script: declare -a projectList=(
    "$path/Services/Catalog/Catalog.API"
    "$path/Services/Basket/Basket.API"
    "$path/Services/Ordering/Ordering.API"
    "$path/Services/Identity/Identity.API"
    "$path/Services/Location/Locations.API"
    "$path/Services/Marketing/Marketing.API"
    "$path/Services/Payment/Payment.API"
    "$path/Web/WebMVC"
    "$path/Web/WebStatus" );
  displayName: 'Build Project List Array'

- script: for project in "${projectList[@]}"
  do
    echo -e "\e[33mWorking on $path/$project"
    pushd $path/$project
    echo -e "\e[33m\tBuilding and publishing $project"
    dotnet publish -c Release -o obj/Docker/publish --verbosity quiet
    popd
  done;
  displayName: 'Building Each Project'
  